# fly.toml app configuration file generated for inving-money-tracker on 2023-09-12T23:57:47+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inving-money-tracker"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
